name = "xovato"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_v2"]

# This line is REQUIRED for Pages + Wrangler to work together
pages_build_output_dir = ".open-next"

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
